# This file is part of the tschm/latex repository
# (https://github.com/tschm/latex).
#
name: 'Sync latex template'
description: 'Sync latex template into a project and create a pull request if needed'
author: 'Thomas Schmelzer'

inputs:
  branch:
    description: 'Branch to sync changes to'
    default: 'sync/update-configs'
    required: false
  commit-message:
    description: 'Commit message for sync'
    default: 'chore: sync files from latex repo'
    required: false

runs:
  using: "composite"
  steps:
    - name: Ensure Git repository
      run: |
        git rev-parse --is-inside-work-tree > /dev/null || {
          echo "❌ Not in a git repository"
          exit 1
        }
      shell: bash

    - name: Download and apply templates
      run: |
        set -euo pipefail

        REPO_URL="https://github.com/tschm/latex"
        TEMP_DIR="$(mktemp -d)"
        trap 'rm -rf "$TEMP_DIR"' EXIT

        echo "📥 Downloading template archive..."
        curl -sSL -o templates.zip "$REPO_URL/archive/refs/heads/main.zip"

        echo "📦 Extracting..."
        unzip -q templates.zip -d "$TEMP_DIR"
        rm -f templates.zip

        EXTRACTED_DIR="${TEMP_DIR}/latex-main"

        echo "🧹 Removing files not needed for client..."

        rm -f "${EXTRACTED_DIR}/action.yml"

        # In this file we specify which files exactly shall be compiled.
        # This depends highly on the exact repo we are in.
        rm -f "${EXTRACTED_DIR}/.github/workflows/latex.yml"

        rm -f "${EXTRACTED_DIR}/README.md"

        # Paper is only there to test the workflows here...
        rm -rf "${EXTRACTED_DIR}/paper"

        echo "📂 Copying to working directory..."
        cp -Rf "${EXTRACTED_DIR}/." .

        echo "✅ Sync complete. Changed files:"
        git status --short || true
      shell: bash
