#!/bin/bash
set -e

# -----------------------------
# Function to escape LaTeX special chars
# -----------------------------
escape_latex() {
  local str="$1"
  str="${str//\\/\\textbackslash{}}"   # backslash
  str="${str//&/\\&}"                  # &
  str="${str//%/\\%}"                  # %
  str="${str//\$/\\\$}"                # $
  str="${str//#/\\#}"                  # #
  str="${str//_/\\_}"                  # _
  str="${str//\{/\\{}"}                # {
  str="${str//\}/\\}}"                 # }
  str="${str//~/\\textasciitilde{}}"   # ~
  str="${str//^/\\textasciicircum{}}"  # ^
  echo "$str"
}

# -----------------------------
# Optional working directory
# -----------------------------
WORKING_DIRECTORY="${WORKING_DIRECTORY:-.}"
cd "$WORKING_DIRECTORY"

# -----------------------------
# Git info
# -----------------------------
COMMIT_SHA=$(git rev-parse --short HEAD)
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
COMMIT_DATE=$(git log -1 --format=%cd --date=short)
TAG_NAME=$(git describe --tags --abbrev=0 2>/dev/null || echo "untagged")

# -----------------------------
# Repository URL
# -----------------------------
REPO_URL=$(git config --get remote.origin.url || echo "")
if [[ -z "$REPO_URL" ]]; then
    echo "Warning: remote.origin.url not found, links may not work."
    REPO_URL="."
fi

# Convert SSH to HTTPS if needed
if [[ "$REPO_URL" =~ ^git@ ]]; then
    REPO_URL=$(echo "$REPO_URL" | sed -E 's#git@(.*):(.*)\.git#https://\1/\2#')
else
    REPO_URL=${REPO_URL%.git}
fi

# -----------------------------
# Escape LaTeX
# -----------------------------
COMMIT_SHA_ESCAPED=$(escape_latex "$COMMIT_SHA")
BRANCH_NAME_ESCAPED=$(escape_latex "$BRANCH_NAME")
COMMIT_DATE_ESCAPED=$(escape_latex "$COMMIT_DATE")
REPO_URL_ESCAPED=$(escape_latex "$REPO_URL")
TAG_NAME_ESCAPED=$(escape_latex "$TAG_NAME")

# -----------------------------
# Generate header.tex
# -----------------------------
cat > header.tex <<EOF
% Auto-generated by make_header.sh
\\usepackage{hyperref}
\\newcommand{\\commitsha}{\\href{${REPO_URL}/-/commit/${COMMIT_SHA_ESCAPED}}{\\texttt{${COMMIT_SHA_ESCAPED}}}}
\\newcommand{\\branchname}{\\href{${REPO_URL}/-/tree/${BRANCH_NAME_ESCAPED}}{\\texttt{${BRANCH_NAME_ESCAPED}}}}
\\newcommand{\\commitdate}{\\texttt{${COMMIT_DATE_ESCAPED}}}
\\newcommand{\\reponame}{\\href{${REPO_URL_ESCAPED}}{\\texttt{${REPO_URL_ESCAPED}}}}
\\newcommand{\\tagname}{\\href{${REPO_URL_ESCAPED}/-/tags}{\\texttt{${TAG_NAME_ESCAPED}}}}
EOF
