#!/bin/bash
set -e

# -----------------------------
# Function to escape LaTeX special characters in visible text
# -----------------------------
escape_latex_text() {
  local str="$1"
  str="${str//&/\\&}"
  str="${str//%/\\%}"
  #str="${str//\$/\\\$}"
  str="${str//#/\\#}"
  str="${str//_/\\_}"
  #str="${str//~/\\textasciitilde{}}"
  #str="${str//^/\\textasciicircum{}}"
  echo "$str"
}

# -----------------------------
# Git info
# -----------------------------
COMMIT_SHA=$(git rev-parse --short HEAD)
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
COMMIT_DATE=$(git log -1 --format=%cd --date=short)
TAG_NAME=$(git describe --tags --abbrev=0 2>/dev/null || echo "untagged")
REPO_URL="${CI_PROJECT_URL:-"https://gitlab.com"}"

echo "COMMIT_SHA: $COMMIT_SHA"
echo "BRANCH_NAME: $BRANCH_NAME"
echo "TAG_NAME: $TAG_NAME"
echo "REPO_URL: $REPO_URL"
echo "COMMIT_DATE: $COMMIT_DATE"

# -----------------------------
# Escape visible text only (not URLs)
# -----------------------------
COMMIT_SHA_TEXT=$(escape_latex_text $COMMIT_SHA)
BRANCH_NAME_TEXT=$(escape_latex_text $BRANCH_NAME)
TAG_NAME_TEXT=$(escape_latex_text $TAG_NAME)
REPO_TEXT=$(escape_latex_text $REPO_URL)
COMMIT_DATE_TEXT=$(escape_latex_text $COMMIT_DATE)

echo "COMMIT_SHA_TEXT: $COMMIT_SHA_TEXT"
echo "BRANCH_NAME_TEXT: $BRANCH_NAME_TEXT"
echo "TAG_NAME_TEXT: $TAG_NAME_TEXT"
echo "REPO_TEXT: $REPO_TEXT"
echo "COMMIT_DATE_TEXT: $COMMIT_DATE_TEXT"

# -----------------------------
# Generate clean header.tex
# -----------------------------
cat > header.tex <<EOF
% Auto-generated by make_header.sh
\\usepackage{hyperref}
\\newcommand{\\commitsha}{\\href{${REPO_URL}/-/commit/${COMMIT_SHA}}{\\texttt{${COMMIT_SHA_TEXT}}}}
\\newcommand{\\branchname}{\\href{${REPO_URL}/-/tree/${BRANCH_NAME}}{\\texttt{${BRANCH_NAME_TEXT}}}}
\\newcommand{\\commitdate}{\\texttt{${COMMIT_DATE_TEXT}}}
\\newcommand{\\reponame}{\\href{${REPO_URL}}{\\texttt{${REPO_TEXT}}}}
\\newcommand{\\tagname}{\\href{${REPO_URL}/-/tags}{\\texttt{${TAG_NAME_TEXT}}}}
EOF
