name: Build LaTeX Document

on:
  workflow_call:
    inputs:
      working-directory:
        description: "Directory containing the LaTeX files"
        required: false
        type: string
        default: "paper"
      tex-file:
        description: "LaTeX file to compile (with or without .tex extension)"
        required: false
        type: string
        default: "document"
    #outputs:
    #  pdf_path:
    #    description: "Path to the compiled PDF files"
    #    value: ${{ jobs.build-latex.outputs.pdf_path }}

jobs:
  build-latex:
    runs-on: ubuntu-latest
    name: Compile LaTeX Document
    #outputs:
    #  pdf_path: "${{ inputs.working-directory }}/compiled"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: '0'

      - name: Run make_header.sh
        run: |
          ./make_header.sh
          cat header.tex
          cp header.tex ${{ inputs.working-directory }}/header.tex
          cat ${{ inputs.working-directory }}/header.tex

      - name: Install Tectonic
        uses: wtfjoke/setup-tectonic@v3

      - name: Compile LaTeX document
        shell: bash
        working-directory: ${{ inputs.working-directory }}
        run: |
          # Extract filename without extension if it has one
          tectonic "${{ inputs.tex-file }}"

          # Store the filename for the next step
          FILENAME=$(echo "${{ inputs.tex-file }}" | sed 's/\.tex$//')
          echo "TEX_FILENAME=${FILENAME}" >> $GITHUB_ENV

      - name: Upload compiled PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TEX_FILENAME }}
          path: ${{ inputs.working-directory }}/${{ env.TEX_FILENAME }}.pdf
