name: Linting LaTeX

on:
  push:

permissions:
  contents: read

jobs:
  lint-latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v5  # Official GitHub checkout action

      #- name: Run ChkTeX
      #  uses: j2kun/chktex-action@v2
      #  with:
      #    lint-all: true # Default: `false`

      - name: Install LaTeX tools
        run: |
          sudo apt-get install -y chktex

      - name: Lint with chktex
        working-directory: paper
        run: chktex -q -n1 -n8 document.tex
